-- Ejecutar en Supabase SQL Editor. Nunca expongas la service_role en el cliente.
create extension if not exists pgcrypto;
create type public.user_role as enum ('user','admin');
create type public.comment_status as enum ('pending','approved','rejected');
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null check (char_length(full_name) between 2 and 60), avatar_url text, role public.user_role not null default 'user', created_at timestamptz not null default now());
create table public.prevention_methods (id uuid primary key default gen_random_uuid(), name text not null unique, description text not null, risk_level text not null, recommendations text not null, examples text not null, what_to_do text not null, published boolean not null default true, created_at timestamptz not null default now());
create table public.threats (id uuid primary key default gen_random_uuid(), name text not null unique, category text not null, what_is text not null, how_spreads text not null, prevention text not null, published boolean not null default true, created_at timestamptz not null default now());
create table public.comments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, body text not null check (char_length(trim(body)) between 1 and 1000 and body !~ '<[^>]+>'), status public.comment_status not null default 'pending', created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.prevention_methods enable row level security; alter table public.threats enable row level security; alter table public.comments enable row level security;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin')$$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),split_part(new.email,'@',1))); return new; end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create policy "read public profiles" on profiles for select to authenticated using (true); create policy "own profile update" on profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid() and role=(select role from profiles where id=auth.uid()));
create policy "read published methods" on prevention_methods for select to authenticated using (published or is_admin()); create policy "admins manage methods" on prevention_methods for all to authenticated using (is_admin()) with check (is_admin());
create policy "read published threats" on threats for select to authenticated using (published or is_admin()); create policy "admins manage threats" on threats for all to authenticated using (is_admin()) with check (is_admin());
create policy "read approved or own comments" on comments for select to authenticated using (status='approved' or user_id=auth.uid() or is_admin()); create policy "create own pending comment" on comments for insert to authenticated with check (user_id=auth.uid() and status='pending'); create policy "edit own pending comment" on comments for update to authenticated using (user_id=auth.uid() and status='pending') with check (user_id=auth.uid() and status='pending'); create policy "admins moderate comments" on comments for update to authenticated using (is_admin()) with check (is_admin()); create policy "delete own or admin" on comments for delete to authenticated using (user_id=auth.uid() or is_admin());
insert into public.prevention_methods(name,description,risk_level,recommendations,examples,what_to_do) values
('Antivirus actualizado','Detecta software malicioso conocido.','Alto','Activa actualizaciones automáticas y análisis periódicos.','Microsoft Defender, Bitdefender.','Aísla el equipo y ejecuta un análisis completo.'),
('Actualizaciones','Corrigen vulnerabilidades del sistema y aplicaciones.','Alto','Instala parches apenas estén disponibles.','Actualizaciones de Windows o navegador.','Actualiza antes de seguir usando un software vulnerable.'),
('Contraseñas únicas','Evitan que una filtración comprometa varias cuentas.','Alto','Usa un gestor y frases largas.','Gestor de contraseñas.','Cambia claves expuestas de inmediato.'),
('Phishing','Reduce el engaño por mensajes falsos.','Alto','Verifica remitente y enlace antes de abrir.','Correo que imita un banco.','No respondas; repórtalo y elimina el mensaje.'),
('Descargas seguras','Evita instaladores modificados.','Alto','Descarga desde sitios oficiales.','Tienda oficial de aplicaciones.','Elimina el archivo y analiza el equipo.'),
('Copias de seguridad','Permiten recuperar datos ante ransomware.','Alto','Usa regla 3-2-1 y prueba restauraciones.','Disco externo desconectado.','Restaura desde una copia limpia.'),
('Firewall','Controla conexiones de red no autorizadas.','Medio','Mantén el firewall activo.','Firewall del sistema.','Bloquea la app o conexión sospechosa.'),
('Doble factor','Añade una barrera ante robo de contraseña.','Alto','Prefiere aplicación autenticadora.','TOTP o llave física.','Revoca sesiones y cambia la contraseña.'),
('Navegación segura','Reduce exposición a sitios maliciosos.','Medio','Comprueba dominio y HTTPS.','Dirección escrita manualmente.','Cierra la pestaña y borra descargas.'),
('USB externos','Evita infecciones por medios removibles.','Medio','Escanea antes de abrir archivos.','Memoria USB ajena.','No ejecutes archivos desconocidos.'),
('Wi-Fi pública','Protege datos en redes compartidas.','Medio','Evita operaciones sensibles o usa VPN.','Red de cafetería.','Desconéctate y olvida la red.'),
('Permisos de apps','Limita accesos innecesarios.','Medio','Revisa permisos periódicamente.','Micrófono en una linterna.','Revoca permisos o desinstala la app.');
insert into public.threats(name,category,what_is,how_spreads,prevention) values ('Ransomware','Malware','Cifra archivos para exigir un pago.','Phishing, vulnerabilidades y descargas.','Copias 3-2-1, parches y filtros.'),('Troyano','Malware','Se presenta como software legítimo.','Instaladores y adjuntos falsos.','Fuentes oficiales y antivirus.'),('Gusano','Malware','Se replica automáticamente en redes.','Redes sin parchear y USB.','Actualizaciones y segmentación.'),('Spyware','Malware','Espía actividad y datos del usuario.','Aplicaciones y extensiones maliciosas.','Revisar permisos y analizar el equipo.'),('Keylogger','Malware','Registra pulsaciones de teclado.','Troyanos y dispositivos físicos.','MFA y protección antimalware.'),('Botnet','Red','Red de dispositivos infectados.','Credenciales débiles y fallos expuestos.','Claves únicas y actualizaciones.'),('Adware','Malware','Muestra publicidad invasiva.','Software empaquetado y extensiones.','Instalación personalizada y revisión.'),('Phishing','Ingeniería social','Suplanta entidades para robar datos.','Correo, SMS o redes sociales.','Verificar remitente y no abrir enlaces dudosos.');
-- Promueve solo una cuenta de confianza después de registrarla: update public.profiles set role='admin' where id='UUID';
